version: '2'
services:
  #######################################
  # MySQL server
  #######################################
  mysql:
    image: mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=typo3
